In [1]:
!pip install leafmap

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: leafmap in /var/data/python/lib/python3.12/site-packages (0.57.10)
Requirement already satisfied: anywidget in /var/data/python/lib/python3.12/site-packages (from leafmap) (0.9.21)
Requirement already satisfied: bqplot in /var/data/python/lib/python3.12/site-packages (from leafmap) (0.12.45)
Requirement already satisfied: duckdb>=1.4.1 in /var/data/python/lib/python3.12/site-packages (from leafmap) (1.4.1)
Requirement already satisfied: folium in /var/data/python/lib/python3.12/site-packages (from leafmap) (0.20.0)
Requirement already satisfied: gdown in /var/data/python/lib/python3.12/site-packages (from leafmap) (5.2.0)
Requirement already satisfied: geojson in /var/data/python/lib/python3.12/site-packages (from leafmap) (3.2.0)
Requirement already satisfied: geopandas in /var/data/python/lib/python3.12/site-packages (from leafmap) (1.1.0)
Requirement already satisfied: ipyevents in /var/data/python/lib/python3.12/site-packages (from leafmap) (2.0.4)
Requirement already satisfied: ipyfilechooser in /var/data/python/lib/python3.12/site-packages (from leafmap) (0.6.0)
Requirement already satisfied: ipyleaflet in /var/data/python/lib/python3.12/site-packages (from leafmap) (0.20.0)
Requirement already satisfied: ipyvuetify in /var/data/python/lib/python3.12/site-packages (from leafmap) (1.11.3)
Requirement already satisfied: ipywidgets in /var/data/python/lib/python3.12/site-packages (from leafmap) (8.1.8)
Requirement already satisfied: maplibre in /var/data/python/lib/python3.12/site-packages (from leafmap) (0.3.5)
Requirement already satisfied: matplotlib in /var/data/python/lib/python3.12/site-packages (from leafmap) (3.10.1)
Requirement already satisfied: numpy in /var/data/python/lib/python3.12/site-packages (from leafmap) (2.3.4)
Requirement already satisfied: pandas in /var/data/python/lib/python3.12/site-packages (from leafmap) (2.3.3)
Requirement already satisfied: plotly in /var/data/python/lib/python3.12/site-packages (from leafmap) (6.4.0)
Requirement already satisfied: pystac-client in /var/data/python/lib/python3.12/site-packages (from leafmap) (0.9.0)
Requirement already satisfied: python-box in /var/data/python/lib/python3.12/site-packages (from leafmap) (7.3.2)
Requirement already satisfied: scooby in /var/data/python/lib/python3.12/site-packages (from leafmap) (0.11.0)
Requirement already satisfied: whiteboxgui in /var/data/python/lib/python3.12/site-packages (from leafmap) (2.3.0)
Requirement already satisfied: xyzservices in /var/data/python/lib/python3.12/site-packages (from leafmap) (2025.10.0)
Requirement already satisfied: psygnal>=0.8.1 in /var/data/python/lib/python3.12/site-packages (from anywidget->leafmap) (0.15.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /var/data/python/lib/python3.12/site-packages (from anywidget->leafmap) (4.15.0)
Requirement already satisfied: comm>=0.1.3 in /var/data/python/lib/python3.12/site-packages (from ipywidgets->leafmap) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /var/data/python/lib/python3.12/site-packages (from ipywidgets->leafmap) (9.6.0)
Requirement already satisfied: traitlets>=4.3.1 in /var/data/python/lib/python3.12/site-packages (from ipywidgets->leafmap) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /var/data/python/lib/python3.12/site-packages (from ipywidgets->leafmap) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /var/data/python/lib/python3.12/site-packages (from ipywidgets->leafmap) (3.0.16)
Requirement already satisfied: decorator in /var/data/python/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->leafmap) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /var/data/python/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->leafmap) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /var/data/python/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->leafmap) (0.19.2)
Requirement already satisfied: matplotlib-inline in /var/data/python/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->leafmap) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /var/data/python/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->leafmap) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /var/data/python/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->leafmap) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /usr/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->leafmap) (2.19.2)
Requirement already satisfied: stack_data in /var/data/python/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->leafmap) (0.6.3)
Requirement already satisfied: wcwidth in /var/data/python/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets->leafmap) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /var/data/python/lib/python3.12/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets->leafmap) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /var/data/python/lib/python3.12/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets->leafmap) (0.7.0)
Requirement already satisfied: traittypes>=0.0.6 in /var/data/python/lib/python3.12/site-packages (from bqplot->leafmap) (0.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /var/data/python/lib/python3.12/site-packages (from pandas->leafmap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /var/data/python/lib/python3.12/site-packages (from pandas->leafmap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /var/data/python/lib/python3.12/site-packages (from pandas->leafmap) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->leafmap) (1.17.0)
Requirement already satisfied: branca>=0.6.0 in /var/data/python/lib/python3.12/site-packages (from folium->leafmap) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /var/data/python/lib/python3.12/site-packages (from folium->leafmap) (3.1.6)
Requirement already satisfied: requests in /var/data/python/lib/python3.12/site-packages (from folium->leafmap) (2.32.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/lib/python3.12/site-packages (from jinja2>=2.9->folium->leafmap) (3.0.2)
Requirement already satisfied: beautifulsoup4 in /var/data/python/lib/python3.12/site-packages (from gdown->leafmap) (4.14.3)
Requirement already satisfied: filelock in /var/data/python/lib/python3.12/site-packages (from gdown->leafmap) (3.20.0)
Requirement already satisfied: tqdm in /var/data/python/lib/python3.12/site-packages (from gdown->leafmap) (4.67.1)
Requirement already satisfied: soupsieve>=1.6.1 in /var/data/python/lib/python3.12/site-packages (from beautifulsoup4->gdown->leafmap) (2.8)
Requirement already satisfied: pyogrio>=0.7.2 in /var/data/python/lib/python3.12/site-packages (from geopandas->leafmap) (0.11.1)
Requirement already satisfied: packaging in /usr/lib/python3.12/site-packages (from geopandas->leafmap) (25.0)
Requirement already satisfied: pyproj>=3.5.0 in /var/data/python/lib/python3.12/site-packages (from geopandas->leafmap) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /var/data/python/lib/python3.12/site-packages (from geopandas->leafmap) (2.1.2)
Requirement already satisfied: certifi in /var/data/python/lib/python3.12/site-packages (from pyogrio>=0.7.2->geopandas->leafmap) (2025.10.5)
Requirement already satisfied: jupyter-leaflet<0.21,>=0.20 in /var/data/python/lib/python3.12/site-packages (from ipyleaflet->leafmap) (0.20.0)
Requirement already satisfied: ipyvue<2,>=1.7 in /var/data/python/lib/python3.12/site-packages (from ipyvuetify->leafmap) (1.11.3)
Requirement already satisfied: eval-type-backport in /var/data/python/lib/python3.12/site-packages (from maplibre->leafmap) (0.3.1)
Requirement already satisfied: pydantic>=2.5.3 in /var/data/python/lib/python3.12/site-packages (from maplibre->leafmap) (2.12.5)
Requirement already satisfied: annotated-types>=0.6.0 in /var/data/python/lib/python3.12/site-packages (from pydantic>=2.5.3->maplibre->leafmap) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /var/data/python/lib/python3.12/site-packages (from pydantic>=2.5.3->maplibre->leafmap) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /var/data/python/lib/python3.12/site-packages (from pydantic>=2.5.3->maplibre->leafmap) (0.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /var/data/python/lib/python3.12/site-packages (from matplotlib->leafmap) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /var/data/python/lib/python3.12/site-packages (from matplotlib->leafmap) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /var/data/python/lib/python3.12/site-packages (from matplotlib->leafmap) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /var/data/python/lib/python3.12/site-packages (from matplotlib->leafmap) (1.4.9)
Requirement already satisfied: pillow>=8 in /var/data/python/lib/python3.12/site-packages (from matplotlib->leafmap) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /var/data/python/lib/python3.12/site-packages (from matplotlib->leafmap) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in /var/data/python/lib/python3.12/site-packages (from plotly->leafmap) (2.10.2)
Requirement already satisfied: pystac>=1.10.0 in /var/data/python/lib/python3.12/site-packages (from pystac[validation]>=1.10.0->pystac-client->leafmap) (1.14.1)
Requirement already satisfied: jsonschema~=4.18 in /var/data/python/lib/python3.12/site-packages (from pystac[validation]>=1.10.0->pystac-client->leafmap) (4.25.1)
Requirement already satisfied: attrs>=22.2.0 in /var/data/python/lib/python3.12/site-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /var/data/python/lib/python3.12/site-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /var/data/python/lib/python3.12/site-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /var/data/python/lib/python3.12/site-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (0.28.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /var/data/python/lib/python3.12/site-packages (from requests->folium->leafmap) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /var/data/python/lib/python3.12/site-packages (from requests->folium->leafmap) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /var/data/python/lib/python3.12/site-packages (from requests->folium->leafmap) (2.5.0)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /var/data/python/lib/python3.12/site-packages (from requests[socks]->gdown->leafmap) (1.7.1)
Requirement already satisfied: executing>=1.2.0 in /var/data/python/lib/python3.12/site-packages (from stack_data->ipython>=6.1.0->ipywidgets->leafmap) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /var/data/python/lib/python3.12/site-packages (from stack_data->ipython>=6.1.0->ipywidgets->leafmap) (3.0.0)
Requirement already satisfied: pure-eval in /var/data/python/lib/python3.12/site-packages (from stack_data->ipython>=6.1.0->ipywidgets->leafmap) (0.2.3)
Requirement already satisfied: ipytree in /var/data/python/lib/python3.12/site-packages (from whiteboxgui->leafmap) (0.2.2)
Requirement already satisfied: whitebox in /var/data/python/lib/python3.12/site-packages (from whiteboxgui->leafmap) (2.3.6)
Requirement already satisfied: Click>=6.0 in /var/data/python/lib/python3.12/site-packages (from whitebox->whiteboxgui->leafmap) (8.3.0)

In [2]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in /var/data/python/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /var/data/python/lib/python3.12/site-packages (from openpyxl) (2.0.0)

In [3]:
import plotly.express as px
import geopandas as gpd
import pandas as pd 
import nbformat
from leafmap import maplibregl
import leafmap

In [4]:
ispi_standoffs = pd.read_excel("data/ISPI - Standoffs in the Central Mediterranean (Crisi in mare).xlsx", header=1)

In [5]:
ispi_standoffs

,crisis number,ship,persons onboard,start date,end date,length of standoff,relocated (agreed),disembarked,where disembarked (Italy),nautical miles from Lampedusa
0,1,Aquarius,629,2018-09-06 00:00:00,17/06/2018,9,0,Spagna,NaN,NaN
1,2,Diciotti,523,15/06/2018,19/06/2018,5,0,Italia,Pozzallo,130.0
2,3,Lifeline,234,21/06/2018,28/06/2018,8,220,Malta,NaN,NaN
3,4,Alexander Maersk,113,22/06/2018,26/06/2018,5,0,Italia,Pozzallo,130.0
4,5,Monte Sperone + Protector,447,13/07/2018,16/07/2018,4,270,Italia,Pozzallo,130.0
...,...,...,...,...,...,...,...,...,...,...
290,Governo Draghi,79,3.891626,5.936709,6,23.103448,185,186,NaN,NaN
291,Governo Meloni,139,10.220588,3.560284,4,36.544118,410,69,NaN,NaN
292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,Dati liberamente utilizzabili. Autori: Matteo ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,You are free to use this data. Authors: Matteo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
ispi_standoffs['disembarked'].unique()

# TODO -> DA GESTIRE I DATI DOVE SONO SUDDIVISI IN PIÙ STATI

array(['Spagna', 'Italia', 'Malta', 'Tunisia', '82 in Italia, 2 a Malta',
       '182 in Italia, 36 a Malta', 'Francia', 'Italia (1 a Malta)', nan,
       'median # migrants rescued per mission', 70, 148, 186, 69],
      dtype=object)

In [7]:
ispi_standoffs['where disembarked (Italy)'].unique()

array([nan, 'Pozzallo', 'Catania', 'Lampedusa', 'Augusta', 'Messina',
       'Taranto', 'Palermo', 'Porto Empedocle', 'Olbia', 'Trapani',
       'Pozallo', 'Salerno', 'Livorno', 'Reggio Calabria', 'Tolone',
       'Bari', 'Gioia Tauro', 'Ravenna', 'Ancona', 'La Spezia',
       'Marina di Carrara', 'Napoli', 'Civitavecchia', 'Ortona',
       'Brindisi', 'Vibo Valentia', 'Marina di Carrara + Livorno',
       'Genova', 'Crotone'], dtype=object)

In [8]:
!pip install geopy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopy in /var/data/python/lib/python3.12/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /var/data/python/lib/python3.12/site-packages (from geopy) (2.1)

In [9]:
cols = ['city']
names = [('Roma'),('Trento'),('Genova'),('Trieste'),('Venezia')]
cities = gpd.GeoDataFrame(names,columns=cols)
geo_cities = gpd.tools.geocode(cities.city, provider="arcgis")

In [10]:
cities_ispi = ispi_standoffs[ispi_standoffs['where disembarked (Italy)'].notna()]
cities_ispi

,crisis number,ship,persons onboard,start date,end date,length of standoff,relocated (agreed),disembarked,where disembarked (Italy),nautical miles from Lampedusa
1,2,Diciotti,523,15/06/2018,19/06/2018,5,0,Italia,Pozzallo,130.0
3,4,Alexander Maersk,113,22/06/2018,26/06/2018,5,0,Italia,Pozzallo,130.0
4,5,Monte Sperone + Protector,447,13/07/2018,16/07/2018,4,270,Italia,Pozzallo,130.0
6,7,Diciotti,177,14/08/2018,25/08/2018,12,50,Italia,Catania,210.0
12,13,Sea-Watch 3,47,19/01/2019,31/01/2019,13,32,Italia,Catania,210.0
...,...,...,...,...,...,...,...,...,...,...
279,280,Nadir,49,20/11/2023,20/11/2023,1,0,Italia,Lampedusa,0.0
280,281,Aurora SAR,45,22/11/2023,22/11/2023,1,0,Italia,Lampedusa,0.0
281,282,Humanity 1,200,30/11/2023,2023-02-12 00:00:00,3,0,Italia,Crotone,330.0
282,283,Geo Barents,44,30/11/2023,2023-03-12 00:00:00,4,0,Italia,Taranto,430.0
283,284,Aurora SAR,45,30/11/2023,30/11/2023,1,0,Italia,Lampedusa,0.0

In [11]:
geo_cities_ispi = gpd.tools.geocode(cities_ispi['where disembarked (Italy)'], provider="arcgis")

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Pozzallo&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Taranto&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Pozzallo&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Pozzallo&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Taranto&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Pozzallo&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Pozzallo&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Palermo&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Porto+Empedocle&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Augusta&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Trapani&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Augusta&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Augusta&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Augusta&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Pozzallo&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Augusta&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Augusta&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Pozzallo&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Augusta&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Augusta&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Livorno&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Messina&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Taranto&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Taranto&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Reggio+Calabria&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Messina&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Catania&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Catania&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Livorno&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Ravenna&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=La+Spezia&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Salerno&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Brindisi&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Civitavecchia&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Livorno&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Ancona&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Marina+di+Carrara&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Ancona&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Marina+di+Carrara+%2B+Livorno&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Trapani&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Ancona&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Napoli&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Pozzallo&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Lampedusa&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Bari&f=json&maxLocations=1

In [12]:
geo_cities_ispi

                      geometry                                   address
1     POINT (14.8457 36.72605)                          Pozzallo, Ragusa
3     POINT (14.8457 36.72605)                          Pozzallo, Ragusa
4     POINT (14.8457 36.72605)                          Pozzallo, Ragusa
6    POINT (15.08783 37.50248)                                   Catania
12   POINT (15.08783 37.50248)                                   Catania
..                         ...                                       ...
279  POINT (12.60982 35.50112)  Lampedusa, Lampedusa e Linosa, Agrigento
280  POINT (12.60982 35.50112)  Lampedusa, Lampedusa e Linosa, Agrigento
281  POINT (17.12715 39.08067)                                   Crotone
282  POINT (17.24006 40.46922)                                   Taranto
283  POINT (12.60982 35.50112)  Lampedusa, Lampedusa e Linosa, Agrigento

[267 rows x 2 columns]

In [13]:
geo_cities_ispi.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [14]:
# ispi_standoff_gpd = ispi_standoffs.merge(geo_cities_ispi)
# ispi_standoff_gpd
ispi_standoff_gpd = gpd.GeoDataFrame(cities_ispi, geometry=geo_cities_ispi.geometry, crs=geo_cities_ispi.crs)

In [15]:
ispi_standoff_gpd

,crisis number,ship,persons onboard,start date,end date,length of standoff,relocated (agreed),disembarked,where disembarked (Italy),nautical miles from Lampedusa,geometry
1,2,Diciotti,523,15/06/2018,19/06/2018,5,0,Italia,Pozzallo,130.0,POINT (14.8457 36.72605)
3,4,Alexander Maersk,113,22/06/2018,26/06/2018,5,0,Italia,Pozzallo,130.0,POINT (14.8457 36.72605)
4,5,Monte Sperone + Protector,447,13/07/2018,16/07/2018,4,270,Italia,Pozzallo,130.0,POINT (14.8457 36.72605)
6,7,Diciotti,177,14/08/2018,25/08/2018,12,50,Italia,Catania,210.0,POINT (15.08783 37.50248)
12,13,Sea-Watch 3,47,19/01/2019,31/01/2019,13,32,Italia,Catania,210.0,POINT (15.08783 37.50248)
...,...,...,...,...,...,...,...,...,...,...,...
279,280,Nadir,49,20/11/2023,20/11/2023,1,0,Italia,Lampedusa,0.0,POINT (12.60982 35.50112)
280,281,Aurora SAR,45,22/11/2023,22/11/2023,1,0,Italia,Lampedusa,0.0,POINT (12.60982 35.50112)
281,282,Humanity 1,200,30/11/2023,2023-02-12 00:00:00,3,0,Italia,Crotone,330.0,POINT (17.12715 39.08067)
282,283,Geo Barents,44,30/11/2023,2023-03-12 00:00:00,4,0,Italia,Taranto,430.0,POINT (17.24006 40.46922)
283,284,Aurora SAR,45,30/11/2023,30/11/2023,1,0,Italia,Lampedusa,0.0,POINT (12.60982 35.50112)

In [16]:
ispi_map = leafmap.Map()

In [17]:
ispi_standoff_gpd = ispi_standoff_gpd.rename(columns={'persons onboard': 'persons_onboard'})

In [18]:
ispi_standoff_gpd.head()['disembarked']

1     Italia
3     Italia
4     Italia
6     Italia
12    Italia
Name: disembarked, dtype: object

In [19]:
'disembarked' in ispi_standoff_gpd.columns

True

In [20]:
ispi_map.add_gdf(ispi_standoff_gpd, point_style={
        "radius": 6,
        "color": "black",
        "fillColor": "red",
        "fillOpacity": 0.7,
    })
ispi_map

Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

In [ ]:
ispi_standoff_gpd['where disembarked (Italy)'].unique()
# TODO -> verificare che la nazione di sbarco sia l'italia, verificare i nomi in modo univoco
# TODO -> SOSTITUIRE POZALLO CON POZZALLO
# todo -> specificare per tutte le voci, il fatto che sia in Italia (E.g. Augusta in U.S.A. KO)

array(['Pozzallo', 'Catania', 'Lampedusa', 'Augusta', 'Messina',
       'Taranto', 'Palermo', 'Porto Empedocle', 'Olbia', 'Trapani',
       'Pozallo', 'Salerno', 'Livorno', 'Reggio Calabria', 'Tolone',
       'Bari', 'Gioia Tauro', 'Ravenna', 'Ancona', 'La Spezia',
       'Marina di Carrara', 'Napoli', 'Civitavecchia', 'Ortona',
       'Brindisi', 'Vibo Valentia', 'Marina di Carrara + Livorno',
       'Genova', 'Crotone'], dtype=object)

In [ ]:
'Porto di ' + ispi_standoff_gpd['where disembarked (Italy)'].unique() + ', Italy'

array(['Porto di Pozzallo, Italia', 'Porto di Catania, Italia',
       'Porto di Lampedusa, Italia', 'Porto di Augusta, Italia',
       'Porto di Messina, Italia', 'Porto di Taranto, Italia',
       'Porto di Palermo, Italia', 'Porto di Porto Empedocle, Italia',
       'Porto di Olbia, Italia', 'Porto di Trapani, Italia',
       'Porto di Pozallo, Italia', 'Porto di Salerno, Italia',
       'Porto di Livorno, Italia', 'Porto di Reggio Calabria, Italia',
       'Porto di Tolone, Italia', 'Porto di Bari, Italia',
       'Porto di Gioia Tauro, Italia', 'Porto di Ravenna, Italia',
       'Porto di Ancona, Italia', 'Porto di La Spezia, Italia',
       'Porto di Marina di Carrara, Italia', 'Porto di Napoli, Italia',
       'Porto di Civitavecchia, Italia', 'Porto di Ortona, Italia',
       'Porto di Brindisi, Italia', 'Porto di Vibo Valentia, Italia',
       'Porto di Marina di Carrara + Livorno, Italia',
       'Porto di Genova, Italia', 'Porto di Crotone, Italia'],
      dtype=object)

In [47]:
ispi_standoff_disembarked_it_list = ispi_standoff_gpd.query("disembarked == 'Italia'")['where disembarked (Italy)'].unique()

In [65]:
type(ispi_standoff_disembarked_it_list)
import numpy as np

ispi_standoff_disembarked_it_list

ispi_standoff_disembarked_it_list = np.delete(ispi_standoff_disembarked_it_list, np.where(ispi_standoff_disembarked_it_list == 'Pozallo'))
ispi_standoff_disembarked_it_list = np.delete(ispi_standoff_disembarked_it_list, np.where(ispi_standoff_disembarked_it_list == 'Marina di Carrara + Livorno'))

# 10
# ispi_standoff_disembarked_it_list[np.where(ispi_standoff_disembarked_it_list == 'Pozallo')]
#np.remove(ispi_standoff_disembarked_it_list, np.where(ispi_standoff_disembarked_it_list == 'Pozallo'))
#ispi_standoff_disembarked_it_list

In [66]:
ispi_standoff_disembarked_it_list

array(['Pozzallo', 'Catania', 'Lampedusa', 'Augusta', 'Taranto',
       'Messina', 'Palermo', 'Porto Empedocle', 'Olbia', 'Trapani',
       'Salerno', 'Livorno', 'Reggio Calabria', 'Bari', 'Gioia Tauro',
       'Ravenna', 'Ancona', 'La Spezia', 'Marina di Carrara',
       'Civitavecchia', 'Ortona', 'Brindisi', 'Napoli', 'Vibo Valentia',
       'Genova', 'Crotone'], dtype=object)

In [72]:
import pandas as pd

cities = pd.Series(
    ispi_standoff_disembarked_it_list,
    name='input_location'
)

geo_cities_ispi = gpd.tools.geocode(
    cities + ', Italy',
    provider='arcgis'
)

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Messina%2C+Italy&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Gioia+Tauro%2C+Italy&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=La+Spezia%2C+Italy&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Genova%2C+Italy&f=json&maxLocations=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)")': /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=Crotone%2C+Italy&f=json&maxLocations=1

In [76]:
geo_cities_ispi['input_location'] = ispi_standoff_disembarked_it_list
geo_cities_ispi

,geometry,address,input_location
0,POINT (14.8457 36.72605),"Pozzallo, Ragusa",Pozzallo
1,POINT (15.08783 37.50248),Catania,Catania
2,POINT (12.60982 35.50112),"Lampedusa, Lampedusa e Linosa, Agrigento",Lampedusa
3,POINT (15.219 37.23375),"Augusta, Siracusa",Augusta
4,POINT (17.24006 40.46922),Taranto,Taranto
5,POINT (15.55552 38.19233),Messina,Messina
6,POINT (13.36147 38.11566),Palermo,Palermo
7,POINT (13.5269 37.28652),"Porto Empedocle, Agrigento",Porto Empedocle
8,POINT (9.48685 40.92251),"Olbia, Sassari",Olbia
9,POINT (12.51463 38.01859),Trapani,Trapani
10,POINT (14.76595 40.67792),Salerno,Salerno
11,POINT (10.30784 43.55189),Livorno,Livorno
12,POINT (15.6502 38.11463),Reggio Calabria,Reggio Calabria
13,POINT (16.87211 41.12591),Bari,Bari
14,POINT (15.89994 38.42494),"Gioia Tauro, Reggio di Calabria",Gioia Tauro
15,POINT (12.19659 44.41574),Ravenna,Ravenna
16,POINT (13.51599 43.61715),Ancona,Ancona
17,POINT (9.82926 44.1067),La Spezia,La Spezia
18,POINT (10.04142 44.03837),"Marina di Carrara, Massa-Carrara",Marina di Carrara
19,POINT (11.79681 42.09118),"Civitavecchia, Roma",Civitavecchia
20,POINT (14.40521 42.35691),"Ortona, Chieti",Ortona
21,POINT (17.93899 40.63618),Brindisi,Brindisi
22,POINT (14.25254 40.83998),Napoli,Napoli
23,POINT (16.09775 38.67555),Vibo Valentia,Vibo Valentia
24,POINT (8.93399 44.40706),Genova,Genova
25,POINT (17.12715 39.08067),Crotone,Crotone

In [84]:
ispi_standoff_disembarked_it_gpd = ispi_standoff_gpd.query("disembarked == 'Italia'")
type(ispi_standoff_disembarked_it_gpd)
ispi_standoff_disembarked_it_gpd.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [85]:
ispi_standoff_disembarked_it_gpd = ispi_standoff_disembarked_it_gpd.drop(columns=['geometry'])

In [ ]:
ispi_standoff_disembarked_it_gpd_MR = ispi_standoff_disembarked_it_gpd.merge(geo_cities_ispi, left_on='where disembarked (Italy)', right_on='input_location')

# TODO NELLA MERGE RICORDARSI CHE I NOMI COMPOSTI O ERRATI RIMARRANO FUORI -> DA SISTEMARE

In [87]:
ispi_standoff_disembarked_it_gpd_MR.head()

,crisis number,ship,persons_onboard,start date,end date,length of standoff,relocated (agreed),disembarked,where disembarked (Italy),nautical miles from Lampedusa,geometry,address,input_location
0,2,Diciotti,523,15/06/2018,19/06/2018,5,0,Italia,Pozzallo,130.0,POINT (14.8457 36.72605),"Pozzallo, Ragusa",Pozzallo
1,4,Alexander Maersk,113,22/06/2018,26/06/2018,5,0,Italia,Pozzallo,130.0,POINT (14.8457 36.72605),"Pozzallo, Ragusa",Pozzallo
2,5,Monte Sperone + Protector,447,13/07/2018,16/07/2018,4,270,Italia,Pozzallo,130.0,POINT (14.8457 36.72605),"Pozzallo, Ragusa",Pozzallo
3,7,Diciotti,177,14/08/2018,25/08/2018,12,50,Italia,Catania,210.0,POINT (15.08783 37.50248),Catania,Catania
4,13,Sea-Watch 3,47,19/01/2019,31/01/2019,13,32,Italia,Catania,210.0,POINT (15.08783 37.50248),Catania,Catania

In [88]:
ispi_standoff_disembarked_it_gpd_MR['end date'] = pd.to_datetime(ispi_standoff_disembarked_it_gpd_MR['end date'])

In [89]:
ispi_standoff_disembarked_it_gpd_MR

,crisis number,ship,persons_onboard,start date,end date,length of standoff,relocated (agreed),disembarked,where disembarked (Italy),nautical miles from Lampedusa,geometry,address,input_location
0,2,Diciotti,523,15/06/2018,2018-06-19,5,0,Italia,Pozzallo,130.0,POINT (14.8457 36.72605),"Pozzallo, Ragusa",Pozzallo
1,4,Alexander Maersk,113,22/06/2018,2018-06-26,5,0,Italia,Pozzallo,130.0,POINT (14.8457 36.72605),"Pozzallo, Ragusa",Pozzallo
2,5,Monte Sperone + Protector,447,13/07/2018,2018-07-16,4,270,Italia,Pozzallo,130.0,POINT (14.8457 36.72605),"Pozzallo, Ragusa",Pozzallo
3,7,Diciotti,177,14/08/2018,2018-08-25,12,50,Italia,Catania,210.0,POINT (15.08783 37.50248),Catania,Catania
4,13,Sea-Watch 3,47,19/01/2019,2019-01-31,13,32,Italia,Catania,210.0,POINT (15.08783 37.50248),Catania,Catania
...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,280,Nadir,49,20/11/2023,2023-11-20,1,0,Italia,Lampedusa,0.0,POINT (12.60982 35.50112),"Lampedusa, Lampedusa e Linosa, Agrigento",Lampedusa
256,281,Aurora SAR,45,22/11/2023,2023-11-22,1,0,Italia,Lampedusa,0.0,POINT (12.60982 35.50112),"Lampedusa, Lampedusa e Linosa, Agrigento",Lampedusa
257,282,Humanity 1,200,30/11/2023,2023-02-12,3,0,Italia,Crotone,330.0,POINT (17.12715 39.08067),Crotone,Crotone
258,283,Geo Barents,44,30/11/2023,2023-03-12,4,0,Italia,Taranto,430.0,POINT (17.24006 40.46922),Taranto,Taranto
259,284,Aurora SAR,45,30/11/2023,2023-11-30,1,0,Italia,Lampedusa,0.0,POINT (12.60982 35.50112),"Lampedusa, Lampedusa e Linosa, Agrigento",Lampedusa

In [91]:
m_ispi_disembarked_italy_endtime = leafmap.Map()

m_ispi_disembarked_italy_endtime.add_gdf_time_slider(
    ispi_standoff_disembarked_it_gpd_MR,
    time_col='end date',
    layer_name='Events' # TODO IL LAYER È IMPORTANTE PER QUANTO RIGUARDA LA GESTIONE INIZIO/FINE STANDOFF
)

m_ispi_disembarked_italy_endtime

ValueError: No time columns found in the GeoDataFrame

In [92]:
ispi_standoff_disembarked_it_gpd_MR['end date'] = pd.to_datetime(
    ispi_standoff_disembarked_it_gpd_MR['end date'],
    errors='coerce'
)

In [93]:
ispi_standoff_disembarked_it_gpd_MR['end date'].dtype

dtype('<M8[ns]')

In [94]:
ispi_standoff_disembarked_it_gpd_MR = (
    ispi_standoff_disembarked_it_gpd_MR
    .rename(columns={'end date': 'end_date'})
)

In [98]:
ispi_standoff_disembarked_it_gpd_MR.columns

Index(['crisis number', 'ship', 'persons_onboard', 'start date', 'end_date',
       'length of standoff', 'relocated (agreed)', 'disembarked',
       'where disembarked (Italy)', 'nautical miles from Lampedusa',
       'geometry', 'address', 'input_location'],
      dtype='object')

In [115]:
import geopandas as gpd
import pandas as pd
from shapely import wkt

def build_wide_temporal_gdf(
    gdf,
    date_col='end_date',
    value_col='persons_onboard',
    location_col='input_location'
):
    gdf = gdf.copy()
    gdf[date_col] = pd.to_datetime(gdf[date_col])

    # geometry -> WKT
    gdf['_geom_wkt'] = gdf.geometry.apply(lambda g: g.wkt)

    # mapping geometry -> input_location
    loc_map = (
        gdf[['_geom_wkt', location_col]]
        .drop_duplicates()
        .groupby('_geom_wkt')[location_col]
        .agg(lambda x: x.iloc[0])
    )

    # pivot temporale
    wide = gdf.pivot_table(
        index='_geom_wkt',
        columns=date_col,
        values=value_col,
        aggfunc='sum'
    )

    # aggiunta input_location
    wide[location_col] = loc_map
    wide = wide.reset_index()

    # Timestamp -> YYYY-MM-DD
    wide.columns = [
        c.strftime('%Y-%m-%d') if isinstance(c, pd.Timestamp) else c
        for c in wide.columns
    ]

    # WKT -> geometry
    wide['geometry'] = wide['_geom_wkt'].apply(wkt.loads)
    wide = wide.drop(columns='_geom_wkt')

    # ordine colonne
    date_cols = [c for c in wide.columns if c not in ['geometry', location_col]]
    wide = wide[['geometry', location_col] + date_cols]

    return gpd.GeoDataFrame(wide, geometry='geometry')

In [116]:
gdf_wide = build_wide_temporal_gdf(
    ispi_standoff_disembarked_it_gpd_MR,
    date_col='end_date',
    value_col='persons_onboard',
    location_col='input_location'
)

In [117]:
gdf_wide

,geometry,input_location,2018-06-19,2018-06-26,2018-07-16,2018-08-25,2019-01-31,2019-02-09,2019-03-11,2019-03-12,...,2023-11-10,2023-11-11,2023-11-14,2023-11-15,2023-11-20,2023-11-22,2023-11-23,2023-11-30,2023-12-01,2023-12-08
0,POINT (10.04142 44.03837),Marina di Carrara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,21,NaN,NaN,NaN
1,POINT (10.30784 43.55189),Livorno,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,POINT (11.79681 42.09118),Civitavecchia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,162,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,POINT (12.19659 44.41574),Ravenna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,57,NaN,NaN,NaN,NaN
4,POINT (12.51463 38.01859),Trapani,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,POINT (12.60982 35.50112),Lampedusa,NaN,NaN,NaN,NaN,NaN,106,NaN,NaN,...,NaN,NaN,NaN,39,49,45,NaN,45,NaN,NaN
6,POINT (13.36147 38.11566),Palermo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,POINT (13.51599 43.61715),Ancona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73,NaN
8,POINT (13.5269 37.28652),Porto Empedocle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60
9,POINT (14.25254 40.83998),Napoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,POINT (14.40521 42.35691),Ortona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,128,NaN,NaN,NaN,NaN,NaN,NaN
11,POINT (14.76595 40.67792),Salerno,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,POINT (14.8457 36.72605),Pozzallo,523,113,447,NaN,NaN,104,243,NaN,...,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46
13,POINT (15.08783 37.50248),Catania,NaN,NaN,NaN,177,47,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,POINT (15.219 37.23375),Augusta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,POINT (15.55552 38.19233),Messina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,POINT (15.6502 38.11463),Reggio Calabria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,POINT (15.89994 38.42494),Gioia Tauro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,POINT (16.09775 38.67555),Vibo Valentia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,POINT (16.87211 41.12591),Bari,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,POINT (17.12715 39.08067),Crotone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,POINT (17.24006 40.46922),Taranto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,POINT (17.93899 40.63618),Brindisi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,POINT (8.93399 44.40706),Genova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,POINT (9.48685 40.92251),Olbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,POINT (9.82926 44.1067),La Spezia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
m_ispi_datetime = leafmap.Map()
m_ispi_datetime.add_gdf_time_slider(gdf_wide, time_interval=0.05, zoom_to_layer=True)

In [119]:
m_ispi_datetime

Map(center=[np.float64(39.958426), np.float64(13.4364899)], controls=(ZoomControl(options=['position', 'zoom_i…